name: "SyncLyrics"
version: "0.0.1"
slug: "synclyrics"
description: "Fetch, store, and display synced lyrics for your Spotify player."
url: "https://github.com/Sebbes84/SyncLyrics"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - "share:rw"
  - "data:rw"
hassio_api: true
homeassistant_api: true
hassio_role: manager
panel_icon: mdi:music-note-bluetooth
panel_title: SyncLyrics
ingress: true
ports:
  8099/tcp: 8099
options:
  spotify_entity: ""
  cache_size_mb: 100
  show_header: true
  show_progress_bar: true
  show_background: true
  game_mode_enabled: false
  lyric_providers: ["lrclib", "musixmatch", "genius"]
  musixmatch_token: ""
  genius_token: ""
  background_url: ""
  cinema_mode: false
  cinema_screen_width: 80
  cinema_screen_height: 60
  cinema_screen_opacity: 70
schema:
  spotify_entity: str
  cache_size_mb: int
  show_header: bool
  show_progress_bar: bool
  show_background: bool
  game_mode_enabled: bool
  lyric_providers: list(str)
  musixmatch_token: str?
  genius_token: str?
  background_url: str?
  cinema_mode: bool
  cinema_screen_width: int
  cinema_screen_height: int
  cinema_screen_opacity: int
